# Generated by Django 2.2.8 on 2020-07-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobs',
            new_name='Job',
        ),
    ]
